service: whatsapp-new-controller

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'dev'}
  region: eu-west-1
  environment:
    NODE_ENV: ${self:custom.nodeEnv.${self:provider.stage}}

custom:
  stages:
    - dev
    - production
  nodeEnv:
    dev: dev
    production: production

functions:
  app:
    handler: main.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'